### ISSUE TITLE
List in an object does not iterate

### ISSUE THREAD

**Issue by jflecool2** [Lepozepo/meteor-publish-with-relations#10]
I think I found a bug. I used the sample of this git.
Here's the data insertion:
`thing_id = Things.insert({
            name: "Thing " + thing,
            obj: {
                obj_list: [
                    {
                        sub_thing: subthing
                    }
                ]
            },
            root_list: [
                {
                    sub_thing: subthing
                }
            ]
        });`
You can see there's 2 arrays of subthings: one on the root of things and one in "obj", which is an object in things.
The root_list will work:
`Meteor.publish("working", function() {
    this.relations({
        collection: Things,
        filter: {},
        mappings: [
            {
                foreign_key: "root_list.sub_thing",
                collection: SubThings
            }
        ]
    });
    return this.ready();
});`

But the obj_list will not work:
`Meteor.publish("notworking", function() {
    this.relations({
        collection: Things,
        filter: {},
        mappings: [
            {
                foreign_key: "obj.obj_list.sub_thing",
                collection: SubThings
            }
        ]
    });
    return this.ready();
});`

Is it "by design" (technically, because how this package is working, it can't be fixed) or is it a bug?
Thanks
JF

**Comment by Lepozepo** [comment]
Definitely a bug, I'll see what I can do but I'm going to patch up lepozepo:cloudinary first. If you can find the bug, a PR would rock!

**Comment by jflecool2** [comment]
Hi,
Finally found a way to get around it.
It is quite simple and doesn't try to change the interesting use of flatten+pluck.
Made some tests and seems to work on these:

- foreign_key:"sub_things.list.obj2.obj3.sub_thing"
- foreign_key:"obj.list.obj2.obj3.sub_things"
- foreign_key:"DirectSubThing"

**Comment by jflecool2** [comment]
You can close this!
