### ISSUE TITLE
Clarify README example

### ISSUE THREAD

**Issue by lorensr** [Lepozepo/meteor-publish-with-relations#2]
Thanks for publishing this fork! I think it would be clearer if the example used more features and was on a topic, similar to the original package. I'm not sure what `foreign_key:"sub_things.deep_things.deep_thing"` means – is that a nested Mongodb object, or a series of keys, each in a different collection? For instance for this model:

```
Meteor.users
  _id
  profile
    name
      first
      last
    bioId

Posts
  userId

Comments
  postId
  userId
```

Is this correct?

```coffeescript
# a user, their bio, their posts, their posts' most recent approved comments,
# and those comments' users
Meteor.publish "user", (userId) ->
  Meteor.publishWithRelations
    handle: this
    collection: Meteor.users
    filter: userId
    mappings: [
      {
        key: "profile.bioId"
        collection: Bios
      }
      {
        foreign_key: "userId"
        collection: Posts
        mappings: [
          {
            foreign_key: "postId"
            collection: Comments
            filter: { approved: true }
            options: {
              limit: 10,
              sort: { createdAt: -1 }
            }
            mappings: [
              {
                key: "userId"
                collection: Meteor.users
              }
            ]
          }
        ]
      }
    ]
```

Also, the README says there is support for arrays, but doesn't give an example of how that is formatted. This is an array of ids? Eg if the Posts/Comments relationship was changed to:

```
Posts
  userId
  comments # array of Comments._id

Comments
  userId
```

would the mapping be this?

```coffeescript
{
  foreign_key: "userId"
  collection: Posts
  mappings: [
    {
      key: "comments"
      collection: Comments
    }
  ]
}
```

**Comment by Lepozepo** [comment]
Ok, `foreign_key` is the key that exists in the foreign collection and `key` is the key that exists in the "current" collection.

The foreign collection is the one you are hooking up your collection to. So in your posts example the code would look more like this:

```javascript
# a user, their bio, their posts, their posts' most recent approved comments,
# and those comments' users
Meteor.publish "user", (userId) ->
  Meteor.publishWithRelations
    handle: this
    collection: Meteor.users
    filter: userId
    mappings: [
      {
        foreign_key: "profile.bioId"
        collection: Bios
      }
      {
        key: "userId"
        collection: Posts
        mappings: [
          {
            key: "postId"
            collection: Comments
            filter: { approved: true }
            options: {
              limit: 10,
              sort: { createdAt: -1 }
            }
            mappings: [
              {
                foreign_key: "userId"
                collection: Meteor.users
              }
            ]
          }
        ]
      }
    ]
```

So you basically got it backwards. Remember that both go to "_id" by default so basically you are stating the relationship in each object by saying "`key` of "_id" from this collection connects to `foreign_key` of "userId" of the parent collection"

Arrays and object arrays are supported which means you can use the normal mongo type queries to create the relationship. Your arrays example will work once you flip foreign_key for key. The parent or child field can be in the shape `["id1","id2","id3"]` or `[{id:"id1"},{id:"id2"},{id:"id3"}]`

Does that make sense?

**Comment by lorensr** [comment]
Yes, thank you! Thought you might like to use that eg model and basic + array examples in README

**Comment by Lepozepo** [comment]
Sweet, thanks ^_^ I want to upgrade this package a bit more. Hopefully after I get around upgrading cloudinary lol.

**Comment by lorensr** [comment]
What upgrades do you have in mind? Nice cloudinary pkg, didn't know about that service. I've been using the slingshot pkg to do client uploads to S3, and imgix. 

Does this pkg automatically notice that the mongo doc `comments` field is an array, or does the mapping key need to be an array, like changing the below line to `foreign_key: ["comments"]`?

```coffeescript
{
  key: "userId"
  collection: Posts
  mappings: [
    {
      foreign_key: "comments"
      collection: Comments
    }
  ]
}
```

Looking at `_.isArray`: https://github.com/svasva/meteor-publish-with-relations/blob/e2620c9b01dfed3a940f5ca9a09be47410682e50/publish_with_relations.coffee#L24

**Comment by Lepozepo** [comment]
It should automatically identify it ^_^

**Comment by Lepozepo** [comment]
How do you like the slingshot package? I built the S3 package before slingshot was released and I'm going to upgrade that one too to support the latest signing method since slingshot does v2 only :/

**Comment by lorensr** [comment]
It's been working fine for me!

**Comment by lorensr** [comment]
(Working so far at least on desktop, mobile web, and cordova – haven't tested it with many users though – haven't launched the app yet.)

I have a data model that I don't think works w/ this package:

```
Games
  player1
  player2

Meteor.users
  follows # array of userIds
```

The query for a list of games of people I follow would be 
```coffeescript
  $or: [
    player1: $in: user.follows
    player2: $in: user.follows
  ]
,
  sort: created: -1
  limit: 100
```

There's no way to specify that in a `mapping`, right? So I have to maintain another collection that has two docs per game, one doc with player1's id and one with player2's id?

```
UsersToGames
  _id # Meteor.users._id
  game # Games._id
```

**Comment by lorensr** [comment]
And I guess I'd need to copy over `created` to `UsersToGames` in order for the sort & limit to work?

**Comment by Lepozepo** [comment]
Hmm, I'm not sure I understand the structure of Games

**Comment by Lepozepo** [comment]
But definitely, the less arrays you have to work with the better off you will find yourself in the future. It'll make your code easier to maintain I believe. Plus you can leverage reactivity better.

**Comment by lorensr** [comment]
Sorry, this wouldn't be getting rid of the follows array. 
I meant that I don't think there's a way to map using just these two collections:
```coffeescript
Meteor.users.find().fetch
[
  {
    _id: 'pid1'
    follows: ['pid2', 'pid3']
  }
]

Games.find().fetch
[
  {
    _id: 'gid1'
    player1: 'pid2'
    player2: 'pid4'
  }
  {
    _id: 'gid2'
    player1: 'pid5'
    player2: 'pid3'
  }
]
```
So I think I need to add this collection:
```coffeescript
UsersToGames.find().fetch()
[
  {
    _id: 'pid2'
    game: 'gid1'
  }
  {
    _id: 'pid4'
    game: 'gid1'
  }
  {
    _id: 'pid5'
    game: 'gid2'
  }
  {
    _id: 'pid3'
    game: 'gid2'
  }
]
```

**Comment by Lepozepo** [comment]
That seems like an awful lot of work for something simple. In this particular case you could instead make the query to Meteor.users and put it in the filter for Games. If you want it to be reactive you could add this package `meteor add lepozepo:reactive-publish` to make it rerun that particular function when it changes.

**Comment by Lepozepo** [comment]
But honestly, I don't think you need reactivity for that part unless you think people will often be changing who they follow while they observe the games for the people they follow, right?

**Comment by lorensr** [comment]
Thanks a lot for letting me pick your brain, this is a great help! 😃 The game feed is the main aspect of the app, and the publication remains throughout the session (which could last between app opens), regardless of what route you're on. So while I agree that there are situations in which reactivity isn't important, it would be good for the feed to update as you follow/unfollow people during your session. 

I think I get what you're suggesting:

```coffeescript
Meteor.reactivePublish 'gameFeed', ->
  me = Meteor.users.findOne @userId, reactive: true

  Games.find
    $or: [
      player1: $in: me.follows
      player2: $in: me.follows
    ]
  ,
    sort: created: -1
    limit: 100
```
Is that what you meant? Going back to your suggestion of removing the array, I could replace the `follows` user field with a `Followers` collection (`from` follows `to`):
```coffeescript
Followers.find().fetch()
{
  _id: ''
  from: 'pid1'
  to: 'pid2'
}  
{
  _id: ''
  from: 'pid1'
  to: 'pid3'
}  

Meteor.reactivePublish 'gameFeed', ->
  followDocs = Followers.find(
    from: @userId
  ,
    reactive: true
  ).fetch()

  followers = _.pluck followDocs, 'to'

  Games.find
    $or: [
      player1: $in: followers
      player2: $in: followers
    ]
  ,
    sort: created: -1
    limit: 100
```
Do you think this should have better performance?

**Comment by Lepozepo** [comment]
I think using the Followers collection is the way to go, especially if a user could have thousands of followers (there's a limit to the size of the array Mongo supports I think). I think adding another field to the games collection could be useful too. Add `players` as an array of both player1 and player2. So then I would do this:

```coffeescript
Meteor.publishWithRelations
  handle:this
  collection:Followers
  filter:
    from:@userId
  mappings:[
    foreign_key:"to"
    key:"players"
    collection:Games
  ]
```

**Comment by lorensr** [comment]
Oh great, a `players` array hadn't occurred to me! I also didn't realize that you can have both `foreign_key` and `key` in the same mapping. Just to confirm, the sort/limit should work – ie, it will give me the 100 most recent out of all followed games, not the most recent 100 from each of the users I follow? 

```coffeescript
Meteor.publishWithRelations
  handle: this
  collection: Followers
  filter:
    from: @userId
  mappings: [
    foreign_key: 'to'
    key: 'players'
    collection: Games
    options: 
      sort: created: -1 
      limit: 100,
  ]
```

**Comment by Lepozepo** [comment]
It should ^_^ I'm going to drop an update in a couple of hours to this package. I found a minor bug in one of my apps (the occurrence is very difficult to replicate) but it should improve performance a bit more.

**Comment by lorensr** [comment]
Thanks again, it's working for me! In some cases it strangely publishes one more than limit. Also noticed the leaving-broken-associations-on-client thing mentioned in the readme, which I don't mind, but would be a nice FR for apps for which it's important to guarantee complete realtime access control.
