### ISSUE TITLE
Further readme explaination

### ISSUE THREAD

**Issue by RamyElkest** [Lepozepo/meteor-publish-with-relations#7]
Hi Lepozepo, thanks for maintaining this.

Can you explain what is means exactly to *break* an association.

> IMPORTANT: When an association is broken, the package will stop all subscriptions to all broken associations but will not remove the association from the client. This means updates to the object with the broken association will not be recorded BUT the object will persist on the client. New associations will be published as expected. (This should not have an impact unless you are doing something with total published counts).

I'm having a problem with reactivity (server publishes full data, and client renders subset, and updates, then something happens in the middle which messes up the template, then data is consistent again, I'm thinking this may have something to do with it)

Thanks

**Comment by Lepozepo** [comment]
It means that if a relationship changes, the subscription stops. So let's say a Product has a ProductDescription and the ID pointing to that description changes. The publisher will stop listening for changes on the description but the description object will still exist. This is an unusual case though where the server is changing things and not the client. What is it that you are trying to do?

Marcelo Reyna
702 769 0639

**Comment by RamyElkest** [comment]
Thanks @Lepozepo, that makes sense :+1: 

I figured out my problem to be with blaze's rendering rather than the subscription, few changes did the trick :)

Many thanks for this package

**Comment by Lepozepo** [comment]
No problem :D
