### ISSUE TITLE
Doesn't work with FS.collection

### ISSUE THREAD

**Issue by RamyElkest** [Lepozepo/meteor-publish-with-relations#8]
For some reason I can't map to FS.collections, I'm guessing something to do with added/changes/removed events?

might be nice to add a disclaimer in the readme if that's indeed the case

<pre>
Meteor.publish('posts', function(id) {
  check(id, String);

  this.relations({
    collection: Meteor.posts,
    filter: {id: id},
    mappings: [
      {
        foreign_key: 'image',
        collection: Images
      }
    ]
  });

  return this.ready();
});
</pre><pre>
Images = new FS.Collection("images", {
  stores: [new FS.Store.GridFS("images", {})],
  filter: {
    allow: {
      contentTypes: ['image/*']
    }
  }
});
</pre>

Thanks

**Comment by Lepozepo** [comment]
Maybe, I wasn't aware of that, I'll add the note for sure

**Comment by RamyElkest** [comment]
sweet, ok it's covered in https://github.com/CollectionFS/Meteor-CollectionFS/issues/198

temp soln is to manually access the filerecord collection  through 'cfs.images.filerecord' 

For this package we use collection._name and luckily collectionFS doesn't assign collection._name

fixed by 
<pre>
Images = new FS.Collection("images");
Images._name = 'cfs.images.filerecord';
</pre>

Thanks

**Comment by RamyElkest** [comment]
actually passing <code>collection: Images.files</code> should suffice, nvm :+1:
